name: Deploy Laravel Project on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get the latest code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: |
          composer install --no-scripts --no-progress --no-suggest

      - name: Update Composer dependencies
        run: |
          composer update --no-scripts --no-progress --no-suggest

      - name: Dump autoload files
        run: composer dump-autoload --optimize

      - name: Generate storage link
        run: php artisan storage:link

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      # Additional steps for Vite and asset compilation
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies and build assets with Vite
        run: |
          npm install
          npm run build  # Adjust this command based on your Vite setup (e.g., npm run dev for development)

      # Deployment step
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server-dir: /
          exclude: |
            .git*
            .gitignored
            \htaccessfile
            \.HTACCESS_PHP.txt
